found a new ad host
arthurgeron/blockYTAds pull request #1
Opened 2017-12-04 20:30 UTC by Ar0xA

2017-12-11 14:58 UTC, arthurgeron requested changes
yt3.gghpt is used to store images, has nothing to do with ads.
r5.sn-32o-guhl.googlevideo.com doesn't seem to break YT, still, I'm going to further test it.

2017-12-11 14:59 UTC, arthurgeron commented on hosts.txt
> +0.0.0.0 yt3.ggpht.com
Should be removed

2018-04-20 11:06 UTC, vitaly-korenkov commented
also, noticed that blocking s.ytimg.com prevents normal functioning.

2018-06-25 17:23 UTC, arthurgeron commented
I've added your suggestion (except for yt3.ggpht.com)
s.ytimg.com has been removed from the list

2018-06-25 17:23 UTC, closed without merging